### PR TITLE
wrap all calls to original dns methods in try/catch blocks

### LINKED ISSUE #5: Can't catch exception for invalid input
When using Node's dns library you can catch errors for invalid input:

```
try {
    require('dns').reverse('something wrong', function() {
        console.log('do something');
    });
} catch (e) {
    console.log('some exception happened');
}
```

Output: `some exception happened`

Doing this with dnscache:

```
dns.js:156
      throw errnoException(process._errno, bindingName);
            ^
Error: getHostByAddr ENOTIMP
    at errnoException (dns.js:37:11)
    at Object.query [as reverse] (dns.js:156:13)
    at C:\work\temp\node_modules\dnscache\lib\index.js:285:35
    at Object._onImmediate (C:\work\temp\node_modules\dnscache\lib\cache.js:121:21)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

### PR DESCRIPTION
**Pull request by timbowhite**
should fix  #5

### CODE REVIEW

**Comment by vsacheti** [comment]
:+1:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by drewfish** [comment]
Uggg... kinda heavy-handed, but sounds like it's necessary.

**Comment by drewfish** [comment]
I'm wondering if there's some kinda wrapper we can write, and instead do something like `backup_object = { lookup : foo(dns.lookup), ...}` where `foo()` creates some kind of async-but-try-catch wrapper.

**Comment by bengl** [comment]
+1

There's some potential performance impact of try/catch blocks, but dnscache is optimizing something much more costly anyway. Also correctness should be valued over minor performance nits.

**Pull request merged**
