### PR TITLE
Meet jshint requirements for tests (`npm run test`) by renaming constructor mod_cache to Mod_cache.

### PR DESCRIPTION
**Pull request by michaeltrollan**
The tests are failing with error `test/testcache.js: line XX, col XX, A constructor name should start with an uppercase letter.`

This pull request corrects that.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by michaeltrollan** [comment]
Signed CLA.

**Comment by drewfish** [comment]
Thanks!

**Comment by drewfish** [comment]
published to npm as dnscache@1.0.1

**Pull request merged**
